apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-game-depl
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-game-depl
  template:
    metadata:
      labels:
        app: cr-game-depl
    spec:
      containers:
        - name: cr-game-depl
          image: alexupenev/croyale-game-service:0.0.4
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: cr-game-service
  namespace: blue
  labels:
    app: cr-game-service
spec:
  type: LoadBalancer
  externalIPs:
      - 18.156.82.236
  selector:
    app: cr-game-depl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080