name: MainWorkflow

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build  -t test-spring-build .

#  Docker:
#    needs: Build
#    runs-on: self-hosted
#
#    steps:
