name: MainWorkflow

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: ./mvnw test

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Build Docker image
        run: docker build  -t ${{ secrets.DOCKER_USERNAME }}/croyale-game-service:0.0.4 .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/croyale-game-service:0.0.4


#  Docker:
#    needs: Build
#    runs-on: self-hosted
#
#    steps:
